sonar.projectKey=Mkots_dnd-roguelike-simulator
sonar.organization=mkots

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info,coverage-ct/lcov.info
sonar.exclusions=src/components/ui/**
sonar.test.exclusions=tests/**
sonar.coverage.exclusions=\
  src/main.tsx,\
  src/App.tsx,\
  src/pages/**,\
  src/lib/telegram.ts,\
  src/engine/index.ts,\
  src/engine/types.ts,\
  src/lib/utils.ts
